name: sampleapi_ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Install Swagger DLLs
      run: dotnet tool install --version 5.6.2 Swashbuckle.AspNetCore.Cli
    - name: Swagger 
      run: dotnet swagger tofile --output swagger.json SampleAPI/bin/Release/netcoreapp3.1/SampleAPI.dll v1
    - name: Run Spectral
      uses: stoplightio/spectral-action@v0.7.0
      with:
        file_glob: './swagger.json'
    - name: Publish
      run: dotnet publish --no-build -c Release -o dotnetcorewebapp 
    - name: Zip
      uses: thedoctor0/zip-release@master
      with: 
        filename: dotnetcorewebapp.zip
        directory: 'dotnetcorewebapp' 
    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dotnetcorewebapp
        path: '**/dotnetcorewebapp.zip'

  deploy_to_DEV:
    name: Deploy DEV
    runs-on: ubuntu-latest
    environment:
      name: DEV

    needs: [build]

    steps:
    - name: download sampleapi
      uses: actions/download-artifact@v2
      with:
        name: dotnetcorewebapp
    - name: Display structure of downloaded files
      run: ls -R
      # Deploy to Azure Web apps (not using slots)
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: SampleAPI-bc01 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: './dotnetcorewebapp/dotnetcorewebapp.zip'
    # az ad sp create-for-rbac --name "github-AzureSponsorship-3e2bea16-63ed-4349-9b9c-fe2f91f8e3d4" --sdk-auth --role contributor --scopes /subscriptions/3e2bea16-63ed-4349-9b9c-fe2f91f8e3d4
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    # APIM - Create the Versioned API before running the deployment    
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $ApiMgmtContext = New-AzApiManagementContext -ResourceGroupName "Samples" -ServiceName "samplebc"
          $newRevision= ${{ github.run_number }}
          $revision = New-AzApiManagementApiRevision -Context $ApiMgmtContext -ApiId "demo-api" -ApiRevision "$newRevision" -SourceApiRevision $apiSpecification.ApiRevision  -ServiceUrl https://samplebc.azurewebsites.net
          Import-AzApiManagementApi -Context $ApiMgmtContext -SpecificationFormat OpenApi -SpecificationUrl https://sampleapi-bc01.azurewebsites.net/swagger/v1/swagger.json -ApiId "sample-api" -ApiRevision $revision.APIRevision -Path sampleapi -ServiceUrl https://sampleapi-bc01.azurewebsites.net
        azPSVersion: '3.1.0'
