name: $(Build.DefinitionName)_1.0.$(year:yy)$(DayOfYear)$(Rev:.r)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --no-build -c Release -o dotnetcorewebapp 
    - name: Compress
      run: compress-archive -path 'dotnetcorewebapp' -destinationpath 'dotnetcorewebapp.zip'
    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dotnetcorewebapp
        path: ./dotnetcorewebapp.zip