name: sampleapi_cd

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: download sampleapi
      uses: actions/download-artifact@v2
      with:
        name: dotnetcorewebapp
    - name: Display structure of downloaded files
      run: ls -R